#!/bin/bash
VIRTENV_HOME=$OPENSHIFT_DEPENDENCIES_DIR/virtualenv/
echo "Running app..."
source $VIRTENV_HOME/bin/activate
nohup {{cookiecutter.app_name}} --host=${OPENSHIFT_DIY_IP} --port=${OPENSHIFT_DIY_PORT} > ${OPENSHIFT_DIY_LOG_DIR}/{{cookiecutter.app_name}}.log 2>&1 &
